[build]
  command = "gem install jekyll bundle && ./workaround.sh"

[[plugins]]
  package = "netlify-plugin-nimbella"

[[redirects]]
  from = "/*"
  to = "https://rodricgm-h4nvfnjgdgg-apigcp.nimbella.io/:splat"
  status = 200
  force = true
